// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeProject.Data;

#nullable disable

namespace OfficeProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522184548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfficeProject.Models.Entities.Accounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaymentsMade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AccountId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.AssignedUsers", b =>
                {
                    b.Property<int>("AssignedUsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignedUsersId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignedUsersId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("AssignedUsers");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Clients", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientContact1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientContact2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClientCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientEmail1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEmail2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSourceNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.DesignPhase", b =>
                {
                    b.Property<int>("DesignTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignTaskId"));

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignTool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MockupLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebDevelopmentId")
                        .HasColumnType("int");

                    b.HasKey("DesignTaskId");

                    b.HasIndex("WebDevelopmentId")
                        .IsUnique();

                    b.ToTable("DesigningPhases");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.DevelopmentPhase", b =>
                {
                    b.Property<int>("DevelopmentTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevelopmentTaskId"));

                    b.Property<string>("CodeRepoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgrammingLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebDevelopmentId")
                        .HasColumnType("int");

                    b.HasKey("DevelopmentTaskId");

                    b.HasIndex("WebDevelopmentId")
                        .IsUnique();

                    b.ToTable("DevelopmentPhases");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.MaintenancePhase", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SystemAffected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebDevelopmentId")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("WebDevelopmentId")
                        .IsUnique();

                    b.ToTable("MaintenancePhase");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.MarketingPhase", b =>
                {
                    b.Property<int>("MarketingTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketingTaskId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketingTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarketingTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("MarketingPhases");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.OthersService", b =>
                {
                    b.Property<int>("OthersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OthersId"));

                    b.Property<string>("ExtraField1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LableName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Post")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("OthersId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OthersService");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.PaymentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ProjectId");

                    b.ToTable("PaymentSchedule");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Products", b =>
                {
                    b.Property<int>("ProductsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductsId"));

                    b.Property<string>("ProductsAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductsCostingPrice")
                        .HasColumnType("int");

                    b.Property<string>("ProductsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductsEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductsModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductsSellingPrice")
                        .HasColumnType("int");

                    b.Property<bool>("ProductsStatus")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Projects", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("BillingType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentIssue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbFollowers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GmbRakning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IgFollowers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("ProjectCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProjectCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjectStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Seo", b =>
                {
                    b.Property<int>("SeoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeoId"));

                    b.Property<double?>("EngagementRate")
                        .HasColumnType("float");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketingTaskId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgressStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ranking")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalFollowers")
                        .HasColumnType("int");

                    b.Property<int?>("TotalLikes")
                        .HasColumnType("int");

                    b.Property<int>("TotalPosts")
                        .HasColumnType("int");

                    b.HasKey("SeoId");

                    b.HasIndex("MarketingTaskId")
                        .IsUnique();

                    b.ToTable("Seo");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.SeoServiceDetails", b =>
                {
                    b.Property<int>("SeoServiceDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeoServiceDetailsId"));

                    b.Property<string>("ExtraField1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("KeyWord")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("SeoServiceDetailsId");

                    b.HasIndex("ServiceId");

                    b.ToTable("SeoServiceDetails");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Services", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal>("AdsBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillingType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraField1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField3")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectsProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPost")
                        .HasColumnType("int");

                    b.Property<int>("TotalReels")
                        .HasColumnType("int");

                    b.HasKey("ServiceId");

                    b.HasIndex("ProductsId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectsProjectId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.SocialMediaHandling", b =>
                {
                    b.Property<int>("SocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialId"));

                    b.Property<double?>("EngagementRate")
                        .HasColumnType("float");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketingTaskId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgressStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalFollowers")
                        .HasColumnType("int");

                    b.Property<int?>("TotalLikes")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPosts")
                        .HasColumnType("int");

                    b.HasKey("SocialId");

                    b.HasIndex("MarketingTaskId")
                        .IsUnique();

                    b.ToTable("SocialMediaHandling");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Transactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.UserRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.WebDevelopment", b =>
                {
                    b.Property<int>("WebDevelopmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebDevelopmentId"));

                    b.Property<DateTime?>("ProjectDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectDomainName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProjectExtendedDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectHandledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProjectHostingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProjectHostingRenewalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProjectHostingRenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("ProjectIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectIssueBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjectIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectServerFtpAssign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectServerIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectServerPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectServerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjectStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WebDevelopmentId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("WebDevelopment");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.WorkRecords", b =>
                {
                    b.Property<int>("WorkRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkRecordId"));

                    b.Property<int>("Ads")
                        .HasColumnType("int");

                    b.Property<string>("ExtraField1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField3")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField4")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField5")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField6")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtraField7")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Post")
                        .HasColumnType("int");

                    b.Property<int>("Reels")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkRecordId");

                    b.HasIndex("ServiceId");

                    b.ToTable("WorkRecords");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.WorkRecordsSeoDetails", b =>
                {
                    b.Property<int>("WorkRecordsSeoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkRecordsSeoId"));

                    b.Property<string>("KeyWord")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("WorkRecordId")
                        .HasColumnType("int");

                    b.HasKey("WorkRecordsSeoId");

                    b.HasIndex("WorkRecordId");

                    b.ToTable("WorkRecordsSeoDetails");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Accounts", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Clients", "Client")
                        .WithOne("Accounts")
                        .HasForeignKey("OfficeProject.Models.Entities.Accounts", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.AssignedUsers", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Projects", "Projects")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeProject.Models.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Clients", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Users", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.DesignPhase", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.WebDevelopment", "WebDevelopment")
                        .WithOne("DesignPhase")
                        .HasForeignKey("OfficeProject.Models.Entities.DesignPhase", "WebDevelopmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebDevelopment");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.DevelopmentPhase", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.WebDevelopment", "WebDevelopment")
                        .WithOne("DevelopmentPhase")
                        .HasForeignKey("OfficeProject.Models.Entities.DevelopmentPhase", "WebDevelopmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebDevelopment");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.MaintenancePhase", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.WebDevelopment", "WebDevelopment")
                        .WithOne("MaintenancePhase")
                        .HasForeignKey("OfficeProject.Models.Entities.MaintenancePhase", "WebDevelopmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebDevelopment");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.MarketingPhase", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Projects", "Projects")
                        .WithMany("MarketingPhase")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.OthersService", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Services", "Services")
                        .WithMany("OthersServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Services");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.PaymentSchedule", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Projects", "Project")
                        .WithMany("PaymentSchedule")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Products", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Projects", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Clients", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeProject.Models.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Seo", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.MarketingPhase", "MarketingPhase")
                        .WithOne("Seo")
                        .HasForeignKey("OfficeProject.Models.Entities.Seo", "MarketingTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketingPhase");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.SeoServiceDetails", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Services", "Services")
                        .WithMany("SeoServiceDetails")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Services");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Services", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeProject.Models.Entities.Projects", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeProject.Models.Entities.Projects", null)
                        .WithMany("Services")
                        .HasForeignKey("ProjectsProjectId");

                    b.Navigation("Products");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.SocialMediaHandling", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.MarketingPhase", "MarketingPhase")
                        .WithOne("SocialMediaHandling")
                        .HasForeignKey("OfficeProject.Models.Entities.SocialMediaHandling", "MarketingTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketingPhase");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Transactions", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Accounts", "Accounts")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeProject.Models.Entities.PaymentSchedule", "PaymentSchedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Accounts");

                    b.Navigation("PaymentSchedule");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.UserRoles", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Users", "Users")
                        .WithMany("UserRoles")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.WebDevelopment", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Projects", "Projects")
                        .WithOne("WebDevelopment")
                        .HasForeignKey("OfficeProject.Models.Entities.WebDevelopment", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.WorkRecords", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.Services", "Services")
                        .WithMany("WorkRecords")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Services");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.WorkRecordsSeoDetails", b =>
                {
                    b.HasOne("OfficeProject.Models.Entities.WorkRecords", "WorkRecords")
                        .WithMany("WorkRecordsSeoDetails")
                        .HasForeignKey("WorkRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkRecords");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Accounts", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Clients", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.MarketingPhase", b =>
                {
                    b.Navigation("Seo");

                    b.Navigation("SocialMediaHandling");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Projects", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("MarketingPhase");

                    b.Navigation("PaymentSchedule");

                    b.Navigation("Services");

                    b.Navigation("WebDevelopment");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Services", b =>
                {
                    b.Navigation("OthersServices");

                    b.Navigation("SeoServiceDetails");

                    b.Navigation("WorkRecords");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.Users", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.WebDevelopment", b =>
                {
                    b.Navigation("DesignPhase");

                    b.Navigation("DevelopmentPhase");

                    b.Navigation("MaintenancePhase");
                });

            modelBuilder.Entity("OfficeProject.Models.Entities.WorkRecords", b =>
                {
                    b.Navigation("WorkRecordsSeoDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
